name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install CUDA
      run: |
        wget "https://developer.nvidia.com/compute/cuda/10.0/Prod/local_installers/cuda_10.0.130_410.48_linux"
        sudo sh cuda_10.0.130_410.48_linux -silent -toolkit
    - name: Install ZED SDK
      run: |
        wget "https://download.stereolabs.com/zedsdk/2.8/ubuntu18"
        sudo sh ubuntu18 --quiet -- silent
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Upgrade PIP
      run: python -m pip install --upgrade pip
    - name: Install Requirements
      run: pip install -r requirements.txt
    - name: Build
      run: python zed-python-api/setup.py build
    - name: Install
      run: python zed-python-api/setup.py install
    - name: Lint
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Unit Test
      run: |
        pip install pytest
        pytest
